### ISSUE TITLE
dragen gvcf merge error

### ISSUE THREAD

**Issue by huangl07** [Illumina/gvcfgenotyper#5]
dear,

   I was using dragen to generate gvcf files ,but gvcfgenotyper errer 
$gvcfgenotyper -l test1.gvcf -f ref/ref.fa -o ./test.gvcfg -O v 
Logging output to gvcfgenotyper.20180701_084513.20534.log
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

the header of my file is
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	RGSM2
chr1	1001	.	C	<NON_REF>	.	.	END=1235	GT:DP:GQ:MIN_DP:PL	0/0:2:0:1:0,0,0
chr1	1236	.	G	<NON_REF>	.	.	END=1237	GT:DP:GQ:MIN_DP:PL	0/0:4:12:4:0,12,158
chr1	1238	.	C	<NON_REF>	.	.	END=1250	GT:DP:GQ:MIN_DP:PL	0/0:4:9:3:0,9,98
chr1	1251	.	C	<NON_REF>	.	.	END=1300	GT:DP:GQ:MIN_DP:PL	0/0:6:12:4:0,12,123
chr1	1301	.	G	<NON_REF>	.	.	END=1301	GT:DP:GQ:MIN_DP:PL	0/0:6:0:6:0,0,185
chr1	1302	.	C	<NON_REF>	.	.	END=1364	GT:DP:GQ:MIN_DP:PL	0/0:6:12:4:0,12,143
chr1	1365	.	A	<NON_REF>	.	.	END=1370	GT:DP:GQ:MIN_DP:PL	0/0:4:9:4:0,9,135
chr1	1371	.	C	<NON_REF>	.	.	END=1372	GT:DP:GQ:MIN_DP:PL	0/0:5:12:5:0,12,180
chr1	1373	.	A	<NON_REF>	.	.	END=1406	GT:DP:GQ:MIN_DP:PL	0/0:4:0:3:0,0,61

**Comment by olest** [comment]
Hi, thanks for the interest in gvfgenotyper! Dragen vcf files are currently not supported but we are planning to support them very soon. Please stay tuned.

**Comment by huangl07** [comment]
and also，gvcf as fileformat=VCFv4.2 by GenomeAnalysisTK HaplotypeCaller were also failed

**Comment by olest** [comment]
Ah, I see where the misunderstanding comes from. GVCFgenotyper supports only VCF files from the Illumina variant caller strelka2. This because GATK and strelka2 write slightly different versions of VCF4.2. The documentation explains this.

For GATK output, I recommend using their GVCF merging solution:

https://software.broadinstitute.org/gatk/documentation/tooldocs/3.6-0/org_broadinstitute_gatk_tools_walkers_variantutils_CombineGVCFs.php

Best wishes, Ole

**Comment by huangl07** [comment]
sure that，I know the GATK GVCF merging but the time is pretty long，I figure that the gvcfgenotyper maybe better

**Comment by olest** [comment]
I'm closing this ticket now, feel free to re-open if you have any more questions.
